# fly.toml app configuration file generated for fkfso-phonebook on 2023-06-16T14:08:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fkfso-phonebook"
primary_region = "ams"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[http_service]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
